name: Deploy ke InfinityFree

on:
  push:
    branches:
      - main 

jobs:
  web-deploy:
    name: 🚀 Kirim File ke Hosting
    runs-on: ubuntu-latest
    steps:
    - name: 📦 Mengambil kodingan terbaru
      uses: actions/checkout@v4
    
    - name: 📂 Mengirim file via FTP
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USER }}
        password: ${{ secrets.FTP_PASSWORD }}
        server-dir: /htdocs/